import factory
from .models import Topic
from django.utils import timezone
import random


class TopicFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Topic

    topic_text = factory.LazyAttribute(
        lambda _: random.choice(
            [
                "C ",
                "Java ",
                "Python ",
                "C++ ",
                "C# ",
                "JavaScript ",
                "PHP ",
                "R ",
                "SQL",
                "Go",
                "Swift",
                "Perl",
                "Assembly language",
                "Visual Basic",
                "Ruby",
                "MATLAB",
                "Objective-C",
                "Rust",
                "Delphi/Object Pascal",
                "Classic Visual Basic",
                "SAS",
                "Scratch",
                "D",
                "Dart",
                "PL/SQL",
                "Logo",
                "COBOL",
                "Kotlin",
                "Julia",
                "ABAP",
                "Scala",
                "Transact-SQL",
                "Scheme",
                "Prolog",
                "Ada",
                "Lisp",
                "Apex",
                "Lua",
                "Fortran",
                "Haskell",
                "Hack",
                "VBScript",
                "TypeScript",
                "AWK",
                "ActionScript",
                "Tcl",
                "Smalltalk",
                "(Visual) FoxPro",
                "Solidity",
                "PowerShell",
                "ABC",
                "Algol",
                "APL",
                "Bash",
                "Carbon",
                "CFML",
                "CHILL",
                "CLIPS",
                "Clojure",
                "CLU",
                "Crystal",
                "Curl",
                "DiBOL",
                "Eiffel",
                "Elixir",
                "Elm",
                "Erlang",
                "F#",
                "Forth",
                "GAMS",
                "Groovy",
                "Icon",
                "Inform",
                "Io",
                "J",
                "JScript",
                "LabVIEW",
                "Ladder Logic",
                "ML",
                "Modula-2",
                "Mojo",
                "MQL5",
                "NATURAL",
                "Nim",
                "OCaml",
                "Occam",
                "OpenCL",
                "PL/I",
                "PureScript",
                "Q",
                "Ring",
                "RPG",
                "S",
                "SPARK",
                "Stata",
                "SystemVerilog",
                "VHDL",
                "Wolfram",
                "X++",
                "Zig",
            ]
        )
    )
    pub_date = factory.LazyFunction(timezone.now)
