# Generated by Django 5.1.4 on 2025-01-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_topic_reference_link_vote_date_voted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='subjectlinks',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date_voted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
