# Generated by Django 5.1.4 on 2025-02-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_vote_date_updated_alter_vote_date_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='current_score',
            field=models.IntegerField(default=0, help_text='This is regularly updated based on submitted votes.'),
        ),
    ]
