# Generated by Django 5.1.4 on 2025-02-03 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_subject_current_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.subject')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.vote')),
            ],
        ),
    ]
