# Generated by Django 5.1.4 on 2025-02-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='rankings',
        ),
        migrations.AddConstraint(
            model_name='ranking',
            constraint=models.UniqueConstraint(fields=('vote', 'order'), name='unique_vote_order'),
        ),
    ]
