# Generated by Django 5.1.4 on 2025-02-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_vote_rankings_ranking_unique_vote_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='new_subjects_allowed',
            field=models.CharField(choices=[('admin', 'Admin Only'), ('suggested', 'Users can suggest new subjects'), ('public', 'All users can add new subjects')], default='admin', max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='publicly_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='publicly_votable',
            field=models.BooleanField(default=False),
        ),
    ]
