# Generated by Django 5.1.4 on 2025-02-08 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_topic_new_subjects_allowed_topic_publicly_visible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_group', models.BooleanField(default=False, help_text='Can create a group for this topic')),
                ('can_update_group', models.BooleanField(default=False, help_text='Can update the group for this topic. This includes adding/removing members, changing the group name, and changing the group description.')),
                ('can_add_users_to_group', models.BooleanField(default=False)),
                ('can_set_group_permissions', models.BooleanField(default=False, help_text='Can set the permissions for a group. This is related to the items in this model. This includes setting the permissions for the group owner, group members, and other users.')),
                ('can_rename_topic', models.BooleanField(default=False)),
                ('can_delete_topic', models.BooleanField(default=False)),
                ('can_update_topic_visible', models.BooleanField(default=False)),
                ('can_update_topic_votable', models.BooleanField(default=False)),
                ('can_update_topic_subject_rules', models.BooleanField(default=False)),
                ('can_create_subjects', models.BooleanField(default=False, help_text="Overrides 'can suggest subjects'.")),
                ('can_suggest_subjects', models.BooleanField(default=False, help_text="'can create subjects' overrides this.")),
                ('can_delete_subjects', models.BooleanField(default=False)),
                ('can_vote_on_subjects', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='new_subjects_allowed',
        ),
        migrations.AddField(
            model_name='topic',
            name='public_new_subjects',
            field=models.BooleanField(default=False, help_text='Should this topic allow new subjects to be added by all users?'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='publicly_visible',
            field=models.BooleanField(default=False, help_text='Should this topic be visible to all users?'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='publicly_votable',
            field=models.BooleanField(default=False, help_text='Should this topic be votable by all users?'),
        ),
        migrations.CreateModel(
            name='TopicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, null=True)),
                ('members', models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='group_owners', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.topic')),
            ],
        ),
    ]
