# Generated by Django 5.1.4 on 2025-02-09 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_permissionset_remove_topicgroup_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='permissionset',
            name='name',
        ),
    ]
