# Generated by Django 5.1.4 on 2025-02-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_permissionset_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicgroup',
            name='can_add_users_to_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='can_create_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='can_create_subjects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='can_delete_subjects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='can_delete_topic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='can_rename_topic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='can_set_group_permissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='can_suggest_subjects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='can_update_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='can_update_topic_subject_rules',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='can_update_topic_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='can_update_topic_votable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='can_vote_on_subjects',
            field=models.BooleanField(default=False),
        ),
    ]
