# Generated by Django 5.1.4 on 2025-02-09 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_delete_topicgrouppermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermissionOptions',
        ),
    ]
