# Generated by Django 5.1.4 on 2025-03-09 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_topic_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='topic',
            name='unique_topic_text_lower',
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('topic_text__iexact', models.F('topic_text'))), fields=('topic_text', 'owner'), name='unique_topic_text_owner'),
        ),
    ]
