# Generated by Django 5.1.4 on 2025-03-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_remove_topic_unique_topic_text_lower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='promoted',
            field=models.BooleanField(default=False, help_text='Used to become the de facto topic for repeats. Often comes from owner of site.'),
        ),
    ]
